[build]
builder = "NIXPACKS"
buildCommand = "pip install torch==2.2.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT core.asgi:application --lifespan off"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
