# Generated by Django 5.2 on 2025-04-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceComparisonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_a', models.ImageField(upload_to='faces/')),
                ('foto_b', models.ImageField(upload_to='faces/')),
                ('model_used', models.CharField(max_length=50)),
                ('similarity_percent', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
