# Generated by Django 5.2 on 2025-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_poselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_image', models.ImageField(upload_to='violations/')),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('violation_type', models.CharField(max_length=50)),
                ('violation_time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fine_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
