# Generated by Django 6.1 on 2026-08-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_person_faceimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForensicLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_original', models.ImageField(upload_to='forensic/originals/')),
                ('image_result', models.ImageField(blank=True, null=True, upload_to='forensic/results/')),
                ('method', models.CharField(choices=[('ela', 'Error Level Analysis'), ('noise', 'Noise Analysis'), ('sharpening', 'Sharpening Detection'), ('median_filter', 'Median Filter Detection'), ('copy_move', 'Copy-Move Detection'), ('jpeg_ghost', 'JPEG Ghost Detection'), ('metadata', 'Metadata Forensics')], max_length=20)),
                ('result_json', models.JSONField(default=dict)),
                ('analysis_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
