# Generated by Django 6.1 on 2026-08-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_forensiclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='ArcFace', max_length=50)),
                ('similarity_threshold', models.FloatField(default=0.4)),
                ('detection_backend', models.CharField(default='opencv', max_length=50)),
                ('enforce_detection', models.BooleanField(default=True)),
                ('align', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Model Settings',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
