# Generated by Django 6.1.1 on 2026-09-14 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0009_camera_building_room_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100, verbose_name='Nama Kamera')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gedung/Lokasi')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ruangan')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lantai')),
                ('stream_url', models.TextField(blank=True, null=True, verbose_name='Stream URL')),
                ('image', models.ImageField(upload_to='camera_scans/')),
                ('model_used', models.CharField(max_length=50, verbose_name='Model Deteksi')),
                ('face_detected', models.BooleanField(default=False, verbose_name='Wajah Terdeteksi')),
                ('face_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Wajah')),
                ('similarity_percent', models.FloatField(default=0.0, verbose_name='Kesamaan (%)')),
                ('detection_method', models.CharField(choices=[('haar', 'Haar Cascade'), ('yolo', 'YOLO'), ('mtcnn', 'MTCNN'), ('opencv_dnn', 'OpenCV DNN')], default='opencv_dnn', max_length=20, verbose_name='Metode Deteksi')),
                ('raw_result', models.JSONField(default=dict, verbose_name='Hasil Mentah')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Pesan Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Scan')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='faceapp.camera', verbose_name='Kamera')),
                ('matched_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_scan_matches', to='faceapp.person', verbose_name='Orang Cocok')),
            ],
            options={
                'verbose_name': 'Log Scan Kamera',
                'verbose_name_plural': 'Log Scan Kamera',
                'ordering': ['-created_at'],
            },
        ),
    ]
