# Generated by Django 6.1.1 on 2026-09-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_add_camera_scan_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsetting',
            name='llm_api_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='LLM API Key'),
        ),
        migrations.AddField(
            model_name='modelsetting',
            name='llm_base_url',
            field=models.CharField(default='https://api.bazaarlink.ai/v1', max_length=255, verbose_name='LLM Base URL'),
        ),
        migrations.AddField(
            model_name='modelsetting',
            name='llm_model_name',
            field=models.CharField(default='google/gemini-3.8-flash', max_length=100, verbose_name='LLM Model'),
        ),
        migrations.AddField(
            model_name='modelsetting',
            name='llm_provider',
            field=models.CharField(default='bazaarlink', max_length=50, verbose_name='LLM Provider'),
        ),
    ]
